apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rvrbk-net-tls
spec:
  secretName: rvrbk-net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: rvrbk.net
  dnsNames:
    - rvrbk.net
    - www.rvrbk.net